export const messages = {
  en: {
    nav: { home: 'Home', image: 'Image Converter', video: 'Video Converter', exif: 'EXIF' },
    footer: { image: 'Image Converter', video: 'Video Converter', exif: 'Export EXIF', privacy: 'All processing happens in your browser · No uploads' },
    home: {
      eyebrow: 'Private browser-based conversion', title: 'Convert media.', titleAccent: 'Keep it yours.', subtitle: 'A focused workspace for batch image and video conversion. Nothing is uploaded; every file is processed on your device.', imageCta: 'Convert images', videoCta: 'Convert videos', sectionEyebrow: 'Choose a workspace', sectionTitle: 'Two converters. Every route.', sectionIntro: 'Choose what you are working with, then select the output format inside the converter.', open: 'Open converter', local: 'Processed locally',
      converters: [{ title: 'Image Converter', description: 'Convert mixed batches of {{formats}} files.' }, { title: 'Video Converter', description: 'Convert mixed batches of {{formats}} videos with FFmpeg running locally.' }],
      benefits: [{ title: 'Local by design', description: 'Your files stay on your device. Conversion happens inside the browser.' }, { title: 'Built for batches', description: 'Add different source formats together and export the entire queue at once.' }, { title: 'No friction', description: 'No account, no upload wait, no watermark, and no server-side file limits.' }],
      metadata: 'Metadata utility', exifTitle: 'Need the data behind your photos?', exifText: 'Inspect image metadata and export EXIF records from an entire batch as JSON.', exifLink: 'Open EXIF Export',
    },
    common: { ad: 'Advertisement', quality: 'Quality', threads: 'Threads', converting: 'Converting…', download: 'Download', downloadZip: 'Download All as ZIP', clear: 'Clear', total: 'Total', done: 'Done', processing: 'Processing', errors: 'Errors', save: 'Save', browse: 'Browse Files', dropAria: 'Drop files here or click to browse', drop: 'Drop files here', crossLink: 'Have a mix of formats? Try the universal converter →', convertCount_one: 'Convert {{count}} file', convertCount_other: 'Convert {{count}} files', remove: 'Remove {{name}}', accepts: 'Accepts {{formats}} · Multiple files · Entire folders' },
    image: { badge: 'Image Converter', title: 'Universal Image', suffix: 'Converter', subtitle: 'Convert {{formats}} images together — entirely in your browser.', dropAria: 'Drop image files here or click to browse', drop: 'Drop images here', dropSub: '{{formats}}', to: 'Convert everything to', queued_one: '{{count}} file queued', queued_other: '{{count}} files queued', incompatible_one: "{{count}} file can't convert to {{format}} and will be skipped — pick a different format or remove it.", incompatible_other: "{{count}} files can't convert to {{format}} and will be skipped — pick a different format or remove them.", proseTitle: 'One page, more image formats', prose: "The converter detects each file automatically, including browser-native images and specialist formats. Pick one destination format and convert even a mixed folder in one batch.", bullets: ["Supports {{formats}} input", 'One output setting controls the whole batch', 'Mixed-format folders are supported', '100% browser-side — nothing is uploaded', 'Download individually or as a single ZIP'] },
    video: { badge: 'Video Converter', title: 'Universal Video', suffix: 'Converter', subtitle: 'Convert {{inputs}} videos to {{outputs}} with FFmpeg running in your browser.', dropAria: 'Drop video files here or click to browse', drop: 'Drop videos here', dropSub: '{{formats}}', to: 'Convert everything to', queued_one: '{{count}} file queued', queued_other: '{{count}} files queued', incompatible_one: "{{count}} file can't convert to {{format}} and will be skipped.", incompatible_other: "{{count}} files can't convert to {{format}} and will be skipped.", cpu: "Video encoding is CPU-heavy — higher isn't always faster", proseTitle: 'Video conversion, entirely in your browser', prose: 'This tool uses FFmpeg compiled to WebAssembly, so nothing is uploaded to a server. Conversion re-encodes video for broad compatibility and may take time for large files.', bullets: ['No upload — 100% local processing via WebAssembly','Supports {{inputs}} input','Exports {{outputs}}','The first conversion takes a little longer while FFmpeg initializes'] },
    exif: { badge: 'Metadata Tool', title: '<em>EXIF</em> Data Viewer & Bulk Export', subtitle: 'Drop any number of photos to extract and export EXIF metadata as JSON files — camera settings, GPS, timestamps and more.', heading: 'What is EXIF data?', description: 'EXIF (Exchangeable Image File Format) stores metadata embedded in photo files: camera model, lens, aperture, shutter speed, ISO, GPS coordinates, and more. Fullstack Media Converter extracts this data from multiple photos at once and exports it as structured JSON.', bullets: ['Bulk extract metadata from entire photo libraries', 'Export as clean JSON for further processing', 'GPS coordinates, timestamp, camera model, and more', 'Fully private — processed in your browser'] },
    titles: { home: 'Fullstack Media Converter — Private Image & Video Converter', image: 'Universal Image Converter | Fullstack Media Converter', video: 'Universal Video Converter | Fullstack Media Converter', exif: 'EXIF Export | Fullstack Media Converter' },
  },
  ja: {
    nav: { home: 'ホーム', image: '画像変換', video: '動画変換', exif: 'EXIF' },
    footer: { image: '画像変換', video: '動画変換', exif: 'EXIF書き出し', privacy: 'すべてブラウザ内で処理・アップロード不要' },
    home: {
      eyebrow: 'ブラウザ内で完結する安全な変換', title: 'メディアを変換。', titleAccent: 'ファイルは手元に。', subtitle: '画像と動画をまとめて変換できるシンプルなワークスペースです。ファイルはアップロードされず、すべてお使いの端末内で処理されます。', imageCta: '画像を変換する', videoCta: '動画を変換する', sectionEyebrow: '変換ツールを選択', sectionTitle: '2つのツールですべての変換に対応', sectionIntro: '画像または動画を選び、変換ページ内で出力形式を指定してください。', open: '変換ツールを開く', local: '端末内で処理',
      converters: [{ title: '画像変換ツール', description: '{{formats}}が混在した画像をまとめて変換します。' }, { title: '動画変換ツール', description: '{{formats}}が混在した動画をFFmpegでまとめて変換します。' }],
      benefits: [{ title: '端末内で安全に処理', description: 'ファイルはお使いの端末から外部へ送信されず、ブラウザ内で変換されます。' }, { title: '一括変換に対応', description: '異なる入力形式をまとめて追加し、変換結果を一度に書き出せます。' }, { title: '登録不要ですぐ使える', description: 'アカウント登録、アップロード待ち、透かし、サーバー側の容量制限はありません。' }],
      metadata: 'メタデータツール', exifTitle: '写真の情報を確認しますか？', exifText: '画像に含まれるEXIF情報を確認し、複数ファイルのデータをJSONでまとめて書き出せます。', exifLink: 'EXIF書き出しを開く',
    },
    common: { ad: '広告', quality: '画質', threads: '同時処理数', converting: '変換中…', download: 'ダウンロード', downloadZip: 'ZIPでまとめて保存', clear: 'すべてクリア', total: '合計', done: '完了', processing: '処理中', errors: 'エラー', save: '保存', browse: 'ファイルを選択', dropAria: 'ファイルをドロップするか、クリックして選択してください', drop: 'ファイルをここにドロップ', crossLink: '複数の形式をまとめて変換する →', convertCount: '{{count}}件を変換', remove: '{{name}}を削除', accepts: '対応形式 {{formats}}・複数ファイル・フォルダー' },
    image: { badge: '画像変換ツール', title: 'かんたん一括', suffix: '画像変換', subtitle: '{{formats}}を端末内でまとめて変換できます。', dropAria: '画像をドロップするか、クリックして選択してください', drop: '画像をここにドロップ', dropSub: '{{formats}}', to: 'すべての画像を次の形式へ変換', queued: '{{count}}件のファイルを追加済み', incompatible: '{{count}}件のファイルは{{format}}へ変換できないためスキップされます。別の形式を選ぶか、対象ファイルを削除してください。', proseTitle: 'より多くの画像形式をこのページで変換', prose: 'ブラウザ標準の画像に加えて専用デコーダーが必要な形式もファイルごとに自動判定します。変換先をひとつ選ぶだけで、異なる形式が混在したフォルダーもまとめて変換できます。', bullets: ['{{formats}}入力に対応', '一括設定で全ファイルの出力形式を指定', '異なる画像形式の混在に対応', 'アップロードせずブラウザ内で処理', '個別保存とZIP一括保存に対応'] },
    video: { badge: '動画変換ツール', title: 'かんたん一括', suffix: '動画変換', subtitle: '{{inputs}}を追加し、{{outputs}}から出力形式を選んでブラウザ内のFFmpegで変換できます。', dropAria: '動画をドロップするか、クリックして選択してください', drop: '動画をここにドロップ', dropSub: '{{formats}}', to: 'すべての動画を次の形式へ変換', queued: '{{count}}件のファイルを追加済み', incompatible: '{{count}}件のファイルは{{format}}へ変換できないためスキップされます。', cpu: '動画変換はCPUを多く使用します。同時処理数を増やしても速くならない場合があります。', proseTitle: '動画もアップロードせずブラウザ内で変換', prose: 'WebAssembly版FFmpegを使用するため、動画がサーバーへ送信されることはありません。互換性を高めるため動画を再エンコードするので、大きなファイルには時間がかかる場合があります。', bullets: ['アップロード不要で端末内処理','{{inputs}}入力に対応','{{outputs}}で出力可能','初回のみFFmpegの準備に少し時間がかかります'] },
    exif: { badge: 'メタデータツール', title: '<em>EXIF</em>情報の確認・一括書き出し', subtitle: '複数の写真からカメラ設定、GPS、撮影日時などのEXIF情報を抽出し、JSONファイルとして書き出します。', heading: 'EXIF情報とは？', description: 'EXIFは写真ファイル内に保存されるメタデータで、カメラ、レンズ、絞り、シャッター速度、ISO、GPSなどの情報を含みます。Fullstack Media Converterなら、複数の写真からこれらを抽出してJSONで書き出せます。', bullets: ['複数の写真からメタデータを一括抽出', '扱いやすいJSON形式で書き出し', 'GPS、撮影日時、カメラ情報などに対応', 'アップロードせずブラウザ内で安全に処理'] },
    titles: { home: 'Fullstack Media Converter — 画像・動画をブラウザで一括変換', image: '画像変換ツール — 一括・アップロード不要 | Fullstack Media Converter', video: '動画変換ツール — MOV・MP4・GIF | Fullstack Media Converter', exif: 'EXIF情報の確認・一括書き出し | Fullstack Media Converter' },
  },
} as const;

export type Messages = typeof messages.en | typeof messages.ja;
